/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * PokemonService API
 * OpenAPI spec version: 0.0.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ListPokemonsResponse,
  Status
} from '../../types/pokemons';





export const pokemonServiceListPokemons = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ListPokemonsResponse>> => {
    
    
    return axios.default.get(
      `http://localhost:8080/v1/pokemons`,options
    );
  }


export const getPokemonServiceListPokemonsQueryKey = () => {
    return [`http://localhost:8080/v1/pokemons`] as const;
    }

    
export const getPokemonServiceListPokemonsQueryOptions = <TData = Awaited<ReturnType<typeof pokemonServiceListPokemons>>, TError = AxiosError<Status>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pokemonServiceListPokemons>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPokemonServiceListPokemonsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof pokemonServiceListPokemons>>> = ({ signal }) => pokemonServiceListPokemons({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof pokemonServiceListPokemons>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PokemonServiceListPokemonsQueryResult = NonNullable<Awaited<ReturnType<typeof pokemonServiceListPokemons>>>
export type PokemonServiceListPokemonsQueryError = AxiosError<Status>


export function usePokemonServiceListPokemons<TData = Awaited<ReturnType<typeof pokemonServiceListPokemons>>, TError = AxiosError<Status>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof pokemonServiceListPokemons>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof pokemonServiceListPokemons>>,
          TError,
          Awaited<ReturnType<typeof pokemonServiceListPokemons>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePokemonServiceListPokemons<TData = Awaited<ReturnType<typeof pokemonServiceListPokemons>>, TError = AxiosError<Status>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pokemonServiceListPokemons>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof pokemonServiceListPokemons>>,
          TError,
          Awaited<ReturnType<typeof pokemonServiceListPokemons>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePokemonServiceListPokemons<TData = Awaited<ReturnType<typeof pokemonServiceListPokemons>>, TError = AxiosError<Status>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pokemonServiceListPokemons>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePokemonServiceListPokemons<TData = Awaited<ReturnType<typeof pokemonServiceListPokemons>>, TError = AxiosError<Status>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof pokemonServiceListPokemons>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPokemonServiceListPokemonsQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




