/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * PokemonService API
 * OpenAPI spec version: 0.0.1
 */

/**
 * Contains an arbitrary serialized message along with a @type that describes the type of the serialized message.
 */
export interface GoogleProtobufAny {
  /** The type of the serialized message. */
  '@type'?: string;
  [key: string]: unknown;
 }
