/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * PokemonService API
 * OpenAPI spec version: 0.0.1
 */

export * from './googleProtobufAny';
export * from './listPokemonsResponse';
export * from './pokemon';
export * from './status';