/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * PokemonService API
 * OpenAPI spec version: 0.0.1
 */
import type { Pokemon } from './pokemon';

export interface ListPokemonsResponse {
  pokemons?: Pokemon[];
}
