// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pokemon.proto

package pokemon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListPokemonsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPokemonsRequest) Reset() {
	*x = ListPokemonsRequest{}
	mi := &file_pokemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPokemonsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPokemonsRequest) ProtoMessage() {}

func (x *ListPokemonsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPokemonsRequest.ProtoReflect.Descriptor instead.
func (*ListPokemonsRequest) Descriptor() ([]byte, []int) {
	return file_pokemon_proto_rawDescGZIP(), []int{0}
}

type Pokemon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pokemon) Reset() {
	*x = Pokemon{}
	mi := &file_pokemon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pokemon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pokemon) ProtoMessage() {}

func (x *Pokemon) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pokemon.ProtoReflect.Descriptor instead.
func (*Pokemon) Descriptor() ([]byte, []int) {
	return file_pokemon_proto_rawDescGZIP(), []int{1}
}

func (x *Pokemon) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pokemon) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListPokemonsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pokemons      []*Pokemon             `protobuf:"bytes,1,rep,name=pokemons,proto3" json:"pokemons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPokemonsResponse) Reset() {
	*x = ListPokemonsResponse{}
	mi := &file_pokemon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPokemonsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPokemonsResponse) ProtoMessage() {}

func (x *ListPokemonsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pokemon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPokemonsResponse.ProtoReflect.Descriptor instead.
func (*ListPokemonsResponse) Descriptor() ([]byte, []int) {
	return file_pokemon_proto_rawDescGZIP(), []int{2}
}

func (x *ListPokemonsResponse) GetPokemons() []*Pokemon {
	if x != nil {
		return x.Pokemons
	}
	return nil
}

var File_pokemon_proto protoreflect.FileDescriptor

const file_pokemon_proto_rawDesc = "" +
	"\n" +
	"\rpokemon.proto\x12\apokemon\"\x15\n" +
	"\x13ListPokemonsRequest\"-\n" +
	"\aPokemon\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\"D\n" +
	"\x14ListPokemonsResponse\x12,\n" +
	"\bpokemons\x18\x01 \x03(\v2\x10.pokemon.PokemonR\bpokemons2_\n" +
	"\x0ePokemonService\x12M\n" +
	"\fListPokemons\x12\x1c.pokemon.ListPokemonsRequest\x1a\x1d.pokemon.ListPokemonsResponse\"\x00B\vZ\t.;pokemonb\x06proto3"

var (
	file_pokemon_proto_rawDescOnce sync.Once
	file_pokemon_proto_rawDescData []byte
)

func file_pokemon_proto_rawDescGZIP() []byte {
	file_pokemon_proto_rawDescOnce.Do(func() {
		file_pokemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pokemon_proto_rawDesc), len(file_pokemon_proto_rawDesc)))
	})
	return file_pokemon_proto_rawDescData
}

var file_pokemon_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pokemon_proto_goTypes = []any{
	(*ListPokemonsRequest)(nil),  // 0: pokemon.ListPokemonsRequest
	(*Pokemon)(nil),              // 1: pokemon.Pokemon
	(*ListPokemonsResponse)(nil), // 2: pokemon.ListPokemonsResponse
}
var file_pokemon_proto_depIdxs = []int32{
	1, // 0: pokemon.ListPokemonsResponse.pokemons:type_name -> pokemon.Pokemon
	0, // 1: pokemon.PokemonService.ListPokemons:input_type -> pokemon.ListPokemonsRequest
	2, // 2: pokemon.PokemonService.ListPokemons:output_type -> pokemon.ListPokemonsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pokemon_proto_init() }
func file_pokemon_proto_init() {
	if File_pokemon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pokemon_proto_rawDesc), len(file_pokemon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pokemon_proto_goTypes,
		DependencyIndexes: file_pokemon_proto_depIdxs,
		MessageInfos:      file_pokemon_proto_msgTypes,
	}.Build()
	File_pokemon_proto = out.File
	file_pokemon_proto_goTypes = nil
	file_pokemon_proto_depIdxs = nil
}
